alias_mapping = {
    "vụ án": "Select * from spp_case where upper(CASENAME)=upper('{value}')",
    "danh sách bị can trong vụ án": """
        SELECT ACCUCODE, FULLNAME, BIRTHDAY, SEX, CRIMDATE, CRTDATE, LAWCODE
        FROM spp_accused
        WHERE CASECODE IN (
            SELECT CASECODE FROM spp_case WHERE UPPER(CASENAME) = UPPER('{value}')
        )
    """,
    "tội danh bị can": "spp_accusedlaw",
    "kháng nghị": "spp_against",
    "kháng cáo": "spp_appeal",
    "bị cáo kháng cáo": "spp_appealacc",
    "luật vụ án": "spp_caselaw",
    "trung tâm luật": "spp_cenlaw",
    "trung tâm luật hình phạt": "spp_cenlawpenalty",
    "trung tâm luật viện kiểm sát": "spp_cenlawpenspp",
    "bản án": "spp_centence",
    "người bị thiệt hại": "spp_damaged",
    "quyết định": "spp_decision",
    "quyết định tư pháp": "spp_decision_judicial",
    "dữ liệu quyết định": "spp_deci_data",
    "thi hành án": "spp_execution",
    "chuyển thi hành án": "spp_executrans",
    "chi tiết câu hỏi thường gặp": "spp_faq_detail",
    "đầu tư": "spp_investment",
    "phán quyết": "spp_judgement",
    "phán quyết viện kiểm sát": "spp_judgementspp",
    "biện pháp ngăn chặn": "spp_prevent_measures",
    "đăng ký bị can": "spp_regacc",
    "đăng ký điều tra viên": "spp_regins",
    "đăng ký": "spp_register",
    "báo cáo kháng cáo": "spp_report_appeal",
    "mối quan hệ viện kiểm sát và công an": "spp_spppol",
    "mối quan hệ viện kiểm sát và tòa án": "spp_sppspc",
    "mối quan hệ viện kiểm sát với viện kiểm sát": "spp_sppspp",
    "thống kê": "spp_statistica",
    "chuyển vụ án": "spp_transfer",
    "vi phạm": "spp_violantion",
    "danh mục kháng nghị": "lst_against",
    "kết quả kháng nghị": "lst_against_result",
    "danh mục kháng cáo": "lst_appeal",
    "quân đội": "lst_army",
    "biên phòng": "lst_borderguards",
    "mã": "lst_code",
    "kết luận": "lst_conclution",
    "quốc gia": "lst_country",
    "quốc gia mới": "lst_country_new",
    "loại quyết định": "lst_decision",
    "loại quyết định (chi tiết)": "lst_decitype",
    "mẫu quyết định": "lst_deci_template",
    "vật chứng": "lst_exhibit",
    "ma túy": "lst_heroin",
    "kiểm sát viên": "lst_inspector",
    "kiến thức": "lst_knowledge",
    "luật": "lst_law",
    "nhóm luật": "lst_lawgroup",
    "luật tổng hợp": "lst_law_gen",
    "luật ma túy": "lst_law_heroin",
    "địa điểm": "lst_location",
    "dân tộc": "lst_nation",
    "nghề nghiệp": "lst_occupation",
    "cơ quan": "lst_office",
    "đảng": "lst_party",
    "hình phạt": "lst_penalty",
    "chính trị": "lst_pol",
    "công an": "lst_police",
    "biện pháp ngăn chặn": "lst_prevent",
    "nhà giam": "lst_prison",
    "cơ quan ban hành": "lst_promulgateorg",
    "kiểm lâm": "lst_ranger",
    "lý do": "lst_reason",
    "tôn giáo": "lst_religion",
    "giải quyết": "lst_resolve",
    "người ký": "lst_signer",
    "tòa án cấp cao": "lst_spc",
    "viện kiểm sát": "lst_spp",
    "chuyển giao": "lst_transfer",
}
